apiVersion: batch/v1
kind: Job
metadata:
  name: smoke-test
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
spec:
  backoffLimit: 10
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
      - name: smoke-test-websocket
        image: {{ .Values.smokeTestImage.repository }}:{{ .Values.smokeTestImage.tag }}
        tty: true
        command: ["smoke-test", "streams.{{ .Values.ingress.dnsZone }}"]
      restartPolicy: OnFailure
