replicaCount: 3

image:
  repository: smartcitiesdata/discovery_streams
  tag: development
  pullPolicy: Always

resources:
  limits:
    memory: 512Mi
    cpu: 300m
  requests:
    memory: 512Mi
    cpu: 100m

smokeTestImage:
  repository: smartcitiesdata/discovery_streams_smoke_test
  tag: development
  pullPolicy: Always

ingress:
  enabled: false
  scheme: ""
  subnets: ""
  securityGroups: ""
  certificateARN: ""
  dnsZone: "localhost"
  root_dns_zone: "localhost"

service:
  type: NodePort
  port: 80
  targetPort: 4000

kafka:
  brokers: "streaming-service-public-kafka-bootstrap.streaming-public:9092"

dashboard:
  title: "COTA Streaming Metrics"
