{
 "title": "COTA Streaming Metrics",
 "description": "Metrics Pertaining to   microservices",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "COTA Presence",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cota_vehicle_positions_presence_count)",
     "legendFormat": "Active Web Sockets Connections"
    },
    {}
   ]
  },
  {
   "title": "Current Active Users",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(cota_vehicle_positions_presence_count)"
    }
   ]
  },
  {
   "title": "Rate Over 5M",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cota_vehicle_positions_records{type=\"inbound\"}[5m])",
     "legendFormat": "Inbound Records"
    },
    {
     "expr": "sum(rate(cota_vehicle_positions_records{type=\"outbound\"}[5m]))",
     "legendFormat": "Outbound Records"
    }
   ]
  },
  {
   "title": "Daily Max  Users",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(cota_vehicle_positions_presence_count)"
    }
   ]
  },
  {
   "title": "Inbound & Outbound Records",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cota_vehicle_positions_records{type=\"outbound\"})",
     "legendFormat": "Outbound Records"
    },
    {
     "expr": "cota_vehicle_positions_records{type=\"inbound\"}",
     "legendFormat": "Inbound Records"
    }
   ]
  }
 ]
}