apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.ingress.subnets }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.ingress.securityGroups }}
    alb.ingress.kubernetes.io/tags: scos.delete.on.teardown=true
    alb.ingress.kubernetes.io/healthcheck-path: /socket/healthcheck
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.ingress.certificateARN }}
spec:
  backend:
    serviceName: {{ .Chart.Name }}
    servicePort: {{ .Values.service.port }}
  rules:
  - host: streams.{{ .Values.ingress.dnsZone }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.service.port }}
  - host: streams.{{ .Values.ingress.root_dns_zone }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.service.port }}
